vim.o.clipboard = "unnamed"
vim.o.cmdheight = 0
vim.o.number = true
vim.o.relativenumber = true
vim.o.expandtab = true
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.tabstop = 2
vim.o.list = true
vim.o.listchars = "tab:┊ "
